{{- if .Values.certificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{.Values.microserviceName}}-cert"
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.certificate.hostname }}
{{- end }}